"""Update resources table fields

Revision ID: 4e1545ca1668
Revises: abdb4e8b5f14
Create Date: 2026-09-01 23:18:42.893651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1545ca1668'
down_revision: Union[str, Sequence[str], None] = 'abdb4e8b5f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('category', sa.String(), nullable=False))
    op.add_column('resources', sa.Column('location', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.add_column('resources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('resources', 'resource_type')
    op.drop_column('resources', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('resources', 'created_at')
    op.drop_column('resources', 'is_available')
    op.drop_column('resources', 'location')
    op.drop_column('resources', 'category')
    # ### end Alembic commands ###
