"""Create resources table

Revision ID: abdb4e8b5f14
Revises: 56f9105ab7ff
Create Date: 2026-09-01 20:04:13.742066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abdb4e8b5f14'
down_revision: Union[str, Sequence[str], None] = '56f9105ab7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('resource_type', sa.String(), nullable=False))
    op.add_column('resources', sa.Column('file_url', sa.String(), nullable=True))
    op.drop_column('resources', 'location')
    op.drop_column('resources', 'is_available')
    op.drop_column('resources', 'created_at')
    op.drop_column('resources', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('resources', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('resources', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('resources', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('resources', 'file_url')
    op.drop_column('resources', 'resource_type')
    # ### end Alembic commands ###
